import { sanitizePhone } from "../global-utils";

export const mapEmployeeToBackend = (formData) => ({
  id: formData.id ? formData.id : Date.now(),
  ci: formData.ci,
  num_employee: formData.numEmployee,
  first_name: formData.firstName,
  second_name: formData.secondName,
  last_name: formData.lastName,
  second_last_name: formData.secondLastName,
  birthdate: formData.birthdate,
  place_of_birth: formData.placeOfBirth,
  nationality: formData.nationality,
  sex: formData.sex,
  marital_status: formData.maritalStatus,
  blood_type: formData.bloodType ?? '',
  email: formData.email,
  mobile_phone: formData.mobilePhone ? sanitizePhone(`${formData.mobilePhoneCode}-${formData.mobilePhone}`) : null,
  home_phone: formData?.homePhone ? `${formData.homePhoneCode}${formData.homePhone}` : null, // sanitizePhone(`${formData.homePhoneCode}-${formData.homePhone}`)
  address: formData.address,
  join_date: formData.joinDate,
  department_id: formData.department,
  subdepartment_id: formData.subDepartment,
  position_id: formData.position,
  user_name: formData.userName,
  user_pass: formData.userPass,
  change_pass_next_login: formData.changePassNextLogin,
  status: formData.status,
  use_meru_link: formData.useMeruLink,
  use_hid_card: formData.useHidCard,
  use_locker: formData.useLocker,
  use_transport: formData.useTransport,
  contacts: formData.contacts?.map(contact => ({
    name: contact.name,
    last_name: contact.lastName,
    relationship: contact.relationship,
    phone: contact.phone,
    address: contact.address,
  })),
  assign_id: formData?.lockerAssingId ?? null
});