export const CATEGORY_CONFIGS = {
  'meru-events': {
    hasStartDate: true,
    hasEndDate: true,
    hasStartTime: true,
    hasEndTime: true,
    hasStatus: true,
    hasLocation: true,
    hasRepeatEvent: true,
    hasCreateAlert: true,
    hasColorinDay: true,
    hasDescription: true,
    hasComments: true,
    isYearly: false,
  },
  'wedding-nights': {
    hasStartDate: true,
    hasEndDate: true,
    hasStartTime: true,
    hasEndTime: true,
    hasStatus: true,
    hasLocation: true,
    hasRepeatEvent: true,
    hasCreateAlert: true,
    hasColorinDay: true,
    hasDescription: true,
    hasComments: true,
    isYearly: false,
  },
  'dinner-heights': {
    hasStartDate: true,
    hasEndDate: false,
    hasStartTime: true,
    hasEndTime: true,
    hasStatus: true,
    hasLocation: true,
    hasRepeatEvent: true,
    hasCreateAlert: true,
    hasColorinDay: true,
    hasDescription: true,
    hasComments: true,
    isYearly: false,
  },
  've-holidays': {
    hasStartDate: true,
    hasEndDate: false,
    hasStartTime: false,
    hasEndTime: false,
    hasStatus: false,
    hasLocation: false,
    hasRepeatEvent: true,
    hasCreateAlert: false,
    hasColorinDay: true,
    hasDescription: true,
    hasComments: false,
    isYearly: true,
  },
  'google-calendar': {
    hasStartDate: true,
    hasEndDate: false,
    hasStartTime: false,
    hasEndTime: false,
    hasStatus: false,
    hasLocation: false,
    hasRepeatEvent: true,
    hasCreateAlert: true,
    hasColorinDay: true,
    hasDescription: true,
    hasComments: false,
    isYearly: true,
  },
  
  'meru-birthdays': {
    hasStartDate: true,
    hasEndDate: false,
    hasStartTime: false,
    hasEndTime: false,
    hasStatus: false,
    hasLocation: false,
    hasRepeatEvent: true,
    hasCreateAlert: false,
    hasColorinDay: false,
    hasDescription: false,
    hasComments: false,
    isYearly: true,
  },
  
  'executive-mod': {
    hasStartDate: true,
    hasEndDate: true,
    hasStartTime: true,
    hasEndTime: true,
    hasStatus: false,
    hasLocation: false,
    hasRepeatEvent: true,
    hasCreateAlert: true,
    hasColorinDay: true,
    hasDescription: true,
    hasComments: true,
    isYearly: false,
  }
};

// Configuración por defecto para categorías nuevas
export const DEFAULT_CONFIG = {
  hasStartDate: true,
  hasEndDate: true,
  hasStartTime: true,
  hasEndTime: true,
  hasStatus: true,
  hasLocation: true,
  hasRepeatEvent: true,
  hasCreateAlert: true,
  hasColorinDay: true,
  hasDescription: true,
  hasComments: true,
  isYearly: false
};